version: "3.3"
services:
  docker-ca:
    build: ./build
    environment:
      - PASS_CA=wut
      - PASS_SERVER=test
      - EASYRSA_REQ_COUNTRY=FR
      - EASYRSA_REQ_PROVINCE=Bretagne
      - EASYRSA_REQ_CITY=RENNES
      - EASYRSA_REQ_ORG=Ryptix
      - EASYRSA_REQ_EMAIL=baptistethi@gmail.com
      - EASYRSA_REQ_OU=rypti
      - EASYRSA_REQ_SIZE=4096

    volumes:
      - ./data:/root/openvpn
